run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    # defaults
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    # additional
    - goimports
    - gosec
    - misspell
    - whitespace

output:
  formats:
    - format: colored-line-number
