language: go
go:
  - 1.13.x

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/mod

before_install:
  - docker pull golangci/golangci-lint:latest
  - make bootstrap

script:
  - make build
  - make test

before_deploy:
  - make checksum

deploy:
  provider: releases
  api_key:
    secure: "lhFhY8vEC1LU04fuVBEL+mES/vH25LlgtYgZvM2OWxCd7aTzNjqQxdTMM+vst9yRZGzW+xJ85iggmFTZU/th10AyQ4LTxqHo+8xyWd8+sZNxUvfDyDzz9uLJi+cK5k6HJ86S4dO6VjNVlzhjJDP/kubRjJ6t0Rafl/JzXo66mRaWe2cLD+bTJNsX6Mgeqwr00LjsNtvbyqslvLX99SL/GVI1uv94Fov0Rt37RVuWZG11dplCv9LYmcm0ESA9hgKmaSpZ/f5/i1jtk70GsiSE4DLEmEeBgrFougFuTp2LscQAyn3zuUxj7HoJeTGiXM2a5sZWCXqyGOyLYKVU8QBaSc0h+fg3T7FOPTxfPdCCIC8LR31W+KLwJ2+VHTrkk5eZ5c0r2GtbJ9YX8Y8dukVrbGeIfGs9H4orYefiXNCSn0xndYhbPvNTbrptdxUbGklw+h7ZJZrZgicur+MPOH1Jg08NfklvqPkGIZPr0mYdgdGJ7NZimoz3WOjd9N3cyJA5rhTCPh8FL3RK6g43XVJg3Qmofv6oQdXVqUHfwmOiM0KS22/IfoWv7qhKL1J4Iev8Gc1CBqwQStE1Qr3BE5tW44TxLMQtfKOT88IubNsCMB0UnZpke4XlMMlVTbhHuMCiBj78RNUCbSpOfIXqlShL03knTKUnTKBhDPikRMybbh4="
  skip_cleanup: true
  file:
    - "_dist/tonnage-$TRAVIS_TAG-darwin-amd64.tar.gz"
    - "_dist/tonnage-$TRAVIS_TAG-darwin-amd64.tar.gz.sha256"
    - "_dist/tonnage-$TRAVIS_TAG-linux-386.tar.gz"
    - "_dist/tonnage-$TRAVIS_TAG-linux-386.tar.gz.sha256"
    - "_dist/tonnage-$TRAVIS_TAG-linux-amd64.tar.gz"
    - "_dist/tonnage-$TRAVIS_TAG-linux-amd64.tar.gz.sha256"
    - "_dist/tonnage-$TRAVIS_TAG-windows-amd64.tar.gz"
    - "_dist/tonnage-$TRAVIS_TAG-windows-amd64.tar.gz.sha256"
  on:
    repo: elementalvoid/tonnage
    # Only build binaries for tagged commits
    tags: true
