language: go
go:
  - 1.13.x

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/mod

before_install:
  - docker pull golangci/golangci-lint:latest
  - make bootstrap

script:
  - make build
  - make test

before_deploy:
  - make checksum

deploy:
  provider: releases
  api_key:
    secure: njnzqA13A1u/xBG+rqOf1SJj9wOYtQjUsTBYSTzQmzAWbuF10B3lihfvoPrQ/ntJzhQimLE6sQJzytKogZHHgqNSt8C5pgm3QZcIF9Cu+ej+3c0lvJMl8WsFfkcimarovK/Yrf9dVvLqewcYL5hn/JE4MKqD3T7dbs2Rn8uvlhVNj1HAO/szEt9zsMPI4Xld3v5z4Rd+uHIJBWFqS8zalrpiefZW9bAmWgoB/omYtp7hYRCW/5HJUqCtp/gP4qHoh2+Kdw9xt13DmVGvufJBpGmolIWtUK3giFfdCMwh/G+El3JNHhYv199tiPNZCh585GM25M2SJmrECk/LDghuBe2cCm5aKZHRF7VhP1vH1YeLxhhs1k6gzc09Pl6B6MKr5iXfJ3aZWQewAg5uKMntbI4a3mqE/9EUJLV9OmrinKBSr4wLSuDGg33rADnTKy+WPjjAnaCJgr1glSR9zCFM/FL0ybFs/1na2bvhUBof3OIm8M8XscViZGOB4RQsggw8YQNPFVN3+05FYXmWrM7dA96TzvTnhIEHLdr0AY/alYXB78BaZowgJQmxLJzj3uHieJNtLHg05i2nvqJjdh3zUAHK8xnHiXmk6KKXsti1rJgiezOcSOA6SqUSkoqb5YKxs2SHLHtrQ3dnKwWdGpG2g84X+GVmIpMdMUwe84pn4c4=
  skip_cleanup: true
  file:
    - "_dist/tonnage-$TRAVIS_TAG-darwin-amd64.tar.gz"
    - "_dist/tonnage-$TRAVIS_TAG-darwin-amd64.tar.gz.sha256"
    - "_dist/tonnage-$TRAVIS_TAG-linux-386.tar.gz"
    - "_dist/tonnage-$TRAVIS_TAG-linux-386.tar.gz.sha256"
    - "_dist/tonnage-$TRAVIS_TAG-linux-amd64.tar.gz"
    - "_dist/tonnage-$TRAVIS_TAG-linux-amd64.tar.gz.sha256"
    - "_dist/tonnage-$TRAVIS_TAG-windows-amd64.tar.gz"
    - "_dist/tonnage-$TRAVIS_TAG-windows-amd64.tar.gz.sha256"
  on:
    repo: elementalvoid/tonnage
    # Only build binaries for tagged commits
    tags: true
